export const ROUTES = {
  HOME: '/',
  PRODUCT: `/products`,
  CHECKOUT: '/checkout',
  CONTACT: '/contact-us',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  FAQ: '/faq',
  FORGET_PASSWORD: '/forget-password',
  CHANGE_PASSWORD: '/account/change-password',
  ACCOUNT: '/account/initial',
  ORDERS: '/account/orders',
  ACCOUNT_SETTING: '/account/initial',
  ADDRESS: '/account/address',
  PAYMENT: '/account/payment',
  HELP_CENTER: '/account/help-center',
  LEGAL_NOTICE: '/account/legal-notice',
  NOTIFICATION: '/account/notification',
  SHOPS: '/shops',
  LOGIN: '/signin',
  SIGN_UP: '/signup',
  SEARCH: '/search',
  PRODUCTS: '/products',
  BUNDLE: '/bundles',
  CATEGORY: '/category',
  ORDER: '/complete-order',
  WISHLIST: '/account/wishlist',
};
